### ISSUE TITLE
WARN react-qr-code@0.1.1 requires a peer of react@~15.3.2 and react-native@^0.38.0

### ISSUE THREAD

**Issue by iegik** [rtkhanas/react-qr-code#5]
> npm WARN react-qr-code@0.1.1 requires a peer of react@~15.3.2 but none was installed.> 
> npm WARN react-qr-code@0.1.1 requires a peer of react-native@^0.38.0 but none was installed.

```
    "react": "15.4.2",
    "react-native": "0.39.2",
```

**Comment by rtkhanas** [comment]
What is the problem?

I may guess that you don't like warnings. Setting react@^15.0.0 and react-native@^0.39.0 should fix those, however I haven't tested this lib with latest RN versions.

Anyway, it should still work well for you now.
