### ISSUE TITLE
Time to upgrade

### ISSUE THREAD

**Issue by weasteam** [rtkhanas/react-qr-code#7]
looks like it does not work with the newest version

```
├── UNMET PEER DEPENDENCY react@15.6.1
├── UNMET PEER DEPENDENCY react-art@^0.15.1
├── UNMET PEER DEPENDENCY react-dom@15.6.1
├── UNMET PEER DEPENDENCY react-native@^0.38.0
└─┬ react-qr-code@0.1.1 
  ├── qr.js@0.0.0 
  └── react-addons-shallow-compare@15.6.2 

npm WARN react-qr-code@0.1.1 requires a peer of react@~15.3.2 but none was installed.
npm WARN react-qr-code@0.1.1 requires a peer of react-art@^0.15.1 but none was installed.
npm WARN react-qr-code@0.1.1 requires a peer of react-dom@~15.3.2 but none was installed.
npm WARN react-qr-code@0.1.1 requires a peer of react-native@^0.38.0 but none was installed.
```

**Comment by rtkhanas** [comment]
Hey @weasteam , I have already update all the dependencies, but haven't published to npm yet. Fortunately you can update to `0.1.2` and get those warning out.

However you may still have one. I have change the `react-art` to a `react-art-svg-renderer`. Unfortunately `react-art` requires the `art` package and and does not support server side rendering and does not work with a `react` v16. A `react-art-svg-renderer` package implements the `react-art` API and renders everything to and SVG using react standard DOM components. However, if you render to canvas and use `react-art` anywhere in your project, you can still is it and this library should work fine.
